/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */
import java.io.ByteArrayOutputStream

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    application
    kotlin("jvm") version "2.1.10"
    id("io.freefair.lombok") version "8.13.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven(url = "https://jitpack.io")
    maven(url = "https://maven.lavalink.dev/releases")
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // Jakarta
    implementation("jakarta.annotation:jakarta.annotation-api:3.0.0")
    implementation("jakarta.json:jakarta.json-api:2.1.3")

    // Kotlin
    implementation(kotlin("stdlib"))
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:2.2.0"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.2.0")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.0")

    // Lombok
    implementation("org.projectlombok:lombok:1.18.38")

    // JSON
    implementation("org.eclipse.parsson:parsson:1.1.7")

    // JDA
    implementation("net.dv8tion:JDA:5.6.1")

    // Jackson dependencies (required by JDA)
    implementation("com.fasterxml.jackson.core:jackson-core:2.19.1")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.19.1")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.19.1")

    // Audio
    implementation("dev.arbjerg:lavaplayer:2.2.4")
    implementation("dev.lavalink.youtube:common:1.13.3")

    // SLF4J
    implementation("org.slf4j:slf4j-api:2.0.17")
    implementation("org.slf4j:slf4j-simple:2.0.17")

    // PostgreSQL JDBC driver
    implementation("org.postgresql:postgresql:42.7.7")

    // HikariCP
    implementation("com.zaxxer:HikariCP:6.3.0")

    // Testing
    implementation("org.mockito:mockito-core:5.18.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
    modularity.inferModulePath = true 
}

application {
    // Define the main class for the application.
    mainModule = "bot.ninetail"
    mainClass = "bot.ninetail.core.Main"
    applicationDefaultJvmArgs = listOf(
        "--enable-preview",
        "--add-modules", "ALL-MODULE-PATH",
        "--add-reads", "bot.ninetail=ALL-UNNAMED"
    )
}

tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.addAll(listOf(
        "--enable-preview",
        "--add-reads", "bot.ninetail=ALL-UNNAMED"
    ))
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<JavaExec> {
    jvmArgs = listOf(
        "--enable-preview", 
        "--add-reads", "bot.ninetail=ALL-UNNAMED",
        "--add-modules", "ALL-MODULE-PATH",
        "--patch-module", "bot.ninetail=./build/classes/java/main"
    )
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "bot.ninetail.core.Main",
            "Automatic-Module-Name" to "bot.ninetail"
        )
    }
}
